config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_prefix => 'my'
  resources :users
  resources :results, param: :user_code
  root to: 'results#index'
  get 'admin/users', to: 'admin#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/result.rb
class Result < ApplicationRecord
	validates :user_code, uniqueness: true
	validates :user_code, presence: true
	def to_param
		"#{user_code}"
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  before_create :set_role
  enum role: [:head_admin, :admin, :user]
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def set_role
  	self.role=2
  	self.approved=0
  end

  def last_admin?
  	@admins=User.where(role: 0)
  	@admins.count==1 and self.head_admin?
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_action :authenticate_user!

	def index
		@users=User.all
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!

end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :set_result, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  before_action :authenticate_user!, except: [:create, :update]

  # GET /results
  # GET /results.json
  def index

    @results = Result.all
  end

  # GET /results/1
  # GET /results/1.json
  def show
  end

  # GET /results/new
  def new
    @result = Result.new
  end

  # GET /results/1/edit
  def edit
  end

  # POST /results
  # POST /results.json
  def create
    if(Result.find_by(user_code: params[:user_code]))
      @result = Result.find_by(user_code: params[:user_code])
      respond_to do |format|
        if @result.update(result_params)
          format.html { redirect_to @result, notice: 'Result was successfully updated.' }
          format.json { render :show, status: :ok, location: @result }
        else
          format.html { render :edit }
          format.json { render json: @result.errors, status: :unprocessable_entity }
        end
      end
    else
      @result = Result.new(result_params)
      respond_to do |format|
        if @result.save
          format.html { redirect_to "https://github.com", notice: 'Result was successfully created.' }
          format.json { render :show, status: :created, location: @result }
        else
          format.html { render :new }
          format.json { render json: @result.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /results/1
  # PATCH/PUT /results/1.json
  def update
    respond_to do |format|
      if @result.update(result_params)
        format.html { redirect_to @result, notice: 'Result was successfully updated.' }
        format.json { render :show, status: :ok, location: @result }
      else
        format.html { render :edit }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /results/1
  # DELETE /results/1.json
  def destroy
    @result.destroy
    respond_to do |format|
      format.html { redirect_to results_url, notice: 'Result was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_result
      @result = Result.find_by(user_code: params[:user_code])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def result_params
      params.require(:result).permit(:clicks, :chocolates, :user_code, :eaten_chocolates)
    end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  def destroy
    @user=User.find(params[:id])
    if current_user.head_admin? or (current_user.admin? and (current_user==@user or @user.user?))
      @user.destroy
      redirect_to admin_users_path
    end
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!

	def update
		@user= User.find(params[:id])
		if params[:approve]
			if current_user.head_admin? or (current_user.admin? and (current_user==@user))
				@user.toggle(:approved).save
			end
		elsif params[:make_admin]
			if current_user.head_admin?
				@user.update!(role: params[:make_admin])
			end
		end
		redirect_to admin_users_path				
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/admin/index.html.erb

<div class="container-fluid">
	<div class="row">
		<diw class="col">
			<br/>
			<%if current_user.approved?%>
				<h1>Users</h1>
				<table>
				  <thead>
				    <tr>
				      <th>Email</th>
				      <th>Role</th>
				      <th>Actions</th>
				      <th>Approved</th>
				    </tr>
				  </thead>

				  <tbody>
				    <% @users.each do |user|  %>
				      <tr class="body">
				      	<td><%= user.email %></td>
				      	<% if current_user.head_admin? and (user==current_user and !current_user.last_admin? or !user.head_admin?) %>
					        <%= form_for(user) do |f| %>
					          	<td><%= f.select :role, User.roles.collect{|r| [r[0].humanize, r[0]]}  ,{}, {name: "make_admin", onchange: "this.form.submit();"}%></td>
					        <% end %>
					    <%else%>
				        <td><%= user.role.titleize %></td>
				        <%end%>

				        <td>
				        <%if (current_user.admin? and user.user?) or (current_user.head_admin? and !user.head_admin?)%>
				        	<%= link_to 'Delete User', user_registration_path(user), method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-danger"%>
				        <%elsif current_user==user%>
				        	<%= link_to "Edit Account", edit_user_registration_path(current_user), class: "btn btn-idle"%>
				        <%end%>
				        </td>
				        <td>	
				        <% if !user.head_admin?%>
					        <%= form_for(user) do |f| %>
					          <%=f.check_box :approved, name: "approve", onchange: "this.form.submit();"%>
					        <% end %>
				        <% end %>
				        </td>
				      </tr>
				    <% end %>
				  </tbody>
				</table>
			<% end %>
		</diw>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Greedy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'cokoloko.ico' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%if user_signed_in?%>
    <ul>
      <li><%= link_to image_tag("cokoloko_transparent.png", size: "35"), root_path %></li>
      <li><%= link_to "Home", root_path%></li>
      <li><%= link_to "Users", admin_users_path%></li>
      <li style="float:right"><%= link_to "Sign Out", destroy_user_session_path, method: :delete%></li>
      <li style="float:right"><%= link_to "Edit Account", edit_user_registration_path(current_user) %></li>
    </ul>
    <%else%>
    <ul>
      <li><%= link_to image_tag("cokoloko_transparent.png", size: "35"), new_user_session_path %></li>
      <li style="float:right"><%= link_to "Log In", new_user_session_path%></li>
      <li style="float:right"><%= link_to "Sign Up", new_user_registration_path%></li>
    </ul>
    <%end%>
  <%= yield %>
  </body>
</html>

app/views/results/_form.html.erb
<%= form_with(model: result, local: true) do |form| %>
  <% if result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
      <% result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :clicks %>
    <%= form.number_field :clicks %>
  </div>

  <div class="field">
    <%= form.label :chocolates %>
    <%= form.number_field :chocolates %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/results/edit.html.erb
<h1>Editing Result</h1>

<%= render 'form', result: @result %>

<%= link_to 'Show', @result %> |
<%= link_to 'Back', results_path %>

app/views/results/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-8">
      <br/>
      <h1>Results</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8">
      <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for user code..">
      <br/>
      <table id="resultsTable">
        <thead>
          <tr>
            <th>User code</th>
            <th>Clicks</th>
            <th>Chocolates Earned</th>
            <th>Chocolates Eaten</th>
            <th>Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @results.each do |result| %>
            <tr>
              <td><%= result.user_code %></td>
              <td><%= result.clicks %></td>
              <td><%= result.chocolates %></td>
              <td><%= result.eaten_chocolates %></td>
              <%if current_user.approved?%>
              <td><%= link_to 'Delete Result', result, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
              <%end%>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-md-4">
      <h3>Total clicks: <%=@results.sum(:clicks)%></h3>
      <h3>Total chocolates: <%=@results.sum(:chocolates)%></h3>
      <h3>Avg clicks: <%= (@results.sum(:clicks).to_f/@results.count).round(2) %></h3>
      <h3>Avg chocolates earned: <%= (@results.sum(:chocolates).to_f/@results.count).round(2) %></h3>
      <h3>Avg chocolates eaten: <%= (@results.sum(:eaten_chocolates).to_f/@results.count).round(2) %></h3>
    </div>
  </div>
</div>

app/views/results/new.html.erb
<h1>New Result</h1>

<%= render 'form', result: @result %>

<%= link_to 'Back', results_path %>

app/views/results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Clicks:</strong>
  <%= @result.clicks %>
</p>

<p>
  <strong>Chocolates:</strong>
  <%= @result.chocolates %>
</p>

<%= link_to 'Edit', edit_result_path(@result) %> |
<%= link_to 'Back', results_path %>